---
spring:
  application:
    name: login
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:9195
management:
  endpoints:
    web:
      exposure:
        include: refresh